// Copyright 2024 LAAS-CNRS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef MOTKIN_FORWARD_COMMAND_CONTROLLER__MOTKIN_FORWARD_COMMAND_CONTROLLER_HPP_
#define MOTKIN_FORWARD_COMMAND_CONTROLLER__MOTKIN_FORWARD_COMMAND_CONTROLLER_HPP_

#include <array>
#include <functional>
#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "hardware_interface/loaned_command_interface.hpp"
#include "hardware_interface/loaned_state_interface.hpp"
#include "motkin_dual_motor_testbed_msgs/msg/board_state.hpp"
// auto-generated by generate_parameter_library
#include "motkin_forward_command_controller/motkin_forward_command_controller_parameters.hpp"
#include "rclcpp/publisher.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"

namespace motkin_forward_command_controller {

// Reuse the same CmdType convention as forward_command_controller.
// The flat data array is ordered as: [pos×n | vel×n | eff×n | gain_kp×n |
// gain_kd×n] for n joints. Per-value NaN entries are silently skipped (partial
// updates).
using CmdType = std_msgs::msg::Float64MultiArray;
using BoardStateMsg = motkin_dual_motor_testbed_msgs::msg::BoardState;

// Number of per-joint state fields in BoardStateMsg: position, velocity,
// effort, gain_kp and gain_kd.
constexpr std::size_t kNumJointStateFields = 5;

/**
 * \brief Forward command controller for MOTKIN joints.
 *
 * Extends the forward_command_controller concept to simultaneously command
 * position, velocity, effort, gain_kp and gain_kd for a set of joints through
 * a single ~/commands topic (std_msgs/Float64MultiArray).
 *
 * Expected data layout for n joints:
 *   data[0..n)       positions
 *   data[n..2n)      velocities
 *   data[2n..3n)     efforts
 *   data[3n..4n)     gains_kp
 *   data[4n..5n)     gains_kd
 *
 * A message whose data size is not exactly 5*n is silently ignored.
 * Individual NaN values within a valid message are skipped per-interface.
 *
 * The controller also claims all the state interfaces of the robot and
 * publishes them on ~/board_state: position, velocity, effort, gain_kp and
 * gain_kd of every joint (the controlled joints first, then the others in the
 * order the hardware exports them), plus the clock, latest_command_index and
 * flags state interfaces of the board GPIO.
 *
 * \param joints Names of the joints to control.
 * \param gpio_name Name of the GPIO exporting the board status.
 *
 * Subscribes to:
 * - \b commands (std_msgs::msg::Float64MultiArray)
 *
 * Publishes to:
 * - \b board_state (motkin_dual_motor_testbed_msgs::msg::BoardState)
 */
class MotkinForwardCommandController
    : public controller_interface::ControllerInterface {
 public:
  MotkinForwardCommandController();

  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::return_type update(
      const rclcpp::Time& time, const rclcpp::Duration& period) override;

 protected:
  using LoanedRef =
      std::reference_wrapper<hardware_interface::LoanedCommandInterface>;

  std::vector<std::string> joint_names_;

  // pre-built interface name lists for command_interface_configuration()
  std::vector<std::string> pos_interface_names_;
  std::vector<std::string> vel_interface_names_;
  std::vector<std::string> eff_interface_names_;
  std::vector<std::string> kp_interface_names_;
  std::vector<std::string> kd_interface_names_;

  // per-type ordered references (populated in on_activate, cleared in
  // on_deactivate)
  std::vector<LoanedRef> pos_interfaces_;
  std::vector<LoanedRef> vel_interfaces_;
  std::vector<LoanedRef> eff_interfaces_;
  std::vector<LoanedRef> kp_interfaces_;
  std::vector<LoanedRef> kd_interfaces_;

  realtime_tools::RealtimeThreadSafeBox<CmdType> rt_command_;
  CmdType joint_commands_;

  rclcpp::Subscription<CmdType>::SharedPtr joints_command_subscriber_;

  // Joint state interfaces published on ~/board_state, in the order of the
  // BoardState joint fields. nullptr when the joint does not export one.
  using JointStateRefs =
      std::array<const hardware_interface::LoanedStateInterface*,
                 kNumJointStateFields>;
  std::vector<JointStateRefs> joint_state_interfaces_;

  // Board GPIO state interfaces. nullptr when not exported.
  const hardware_interface::LoanedStateInterface* gpio_clock_ = nullptr;
  const hardware_interface::LoanedStateInterface* gpio_index_ = nullptr;
  const hardware_interface::LoanedStateInterface* gpio_flags_ = nullptr;

  rclcpp::Publisher<BoardStateMsg>::SharedPtr board_state_publisher_;
  std::unique_ptr<realtime_tools::RealtimePublisher<BoardStateMsg>>
      rt_board_state_publisher_;
  BoardStateMsg board_state_msg_;

  void publish_board_state(const rclcpp::Time& time);

 private:
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

}  // namespace motkin_forward_command_controller

#endif  // MOTKIN_FORWARD_COMMAND_CONTROLLER__MOTKIN_FORWARD_COMMAND_CONTROLLER_HPP_
