// Copyright 2026 LAAS-CNRS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef MOTKIN_FIVE_BAR_FORCE_VELOCITY_CONTROLLER__MOTKIN_FIVE_BAR_FORCE_VELOCITY_CONTROLLER_HPP_
#define MOTKIN_FIVE_BAR_FORCE_VELOCITY_CONTROLLER__MOTKIN_FIVE_BAR_FORCE_VELOCITY_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/wrench_stamped.hpp"
#include "hardware_interface/loaned_command_interface.hpp"
#include "hardware_interface/loaned_state_interface.hpp"
// auto-generated by generate_parameter_library
#include "motkin_five_bar_force_velocity_controller/five_bar_kinematics.hpp"
#include "motkin_five_bar_force_velocity_controller/motkin_five_bar_force_velocity_controller_parameters.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"

namespace motkin_five_bar_force_velocity_controller {

/**
 * \brief Endpoint force-to-velocity controller for the five-bar testbed.
 *
 * Implements qdot = J^T f_c: reads the current motor_1/motor_2 positions
 * from their state interfaces, reads a contact force f_c = (fx, fy) at
 * the five-bar closing point (expressed in the (x, y) plane of
 * `case`) from the \b contact_force topic
 * (geometry_msgs/msg/WrenchStamped), computes the analytical five-bar
 * Jacobian J (see five_bar_kinematics.hpp -- no Pinocchio involved) and
 * commands qdot = J^T f_c as a velocity setpoint on both actuated
 * joints, holding position at the currently measured value (so that
 * gain_kp only acts as an anti-drift term) and gain_kd as the gain that
 * actually realizes the commanded velocity.
 *
 * Subscribes to:
 * - \b contact_force (geometry_msgs::msg::WrenchStamped)
 */
class MotkinFiveBarForceVelocityController
    : public controller_interface::ControllerInterface {
 public:
  MotkinFiveBarForceVelocityController();

  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::return_type update(
      const rclcpp::Time& time, const rclcpp::Duration& period) override;

 protected:
  using LoanedCmdRef =
      std::reference_wrapper<hardware_interface::LoanedCommandInterface>;
  using LoanedStateRef =
      std::reference_wrapper<hardware_interface::LoanedStateInterface>;

  std::string left_joint_name_;
  std::string right_joint_name_;
  FiveBarGeometry geometry_;

  // command interface refs, per joint (left, right)
  std::vector<LoanedCmdRef> pos_cmd_;
  std::vector<LoanedCmdRef> vel_cmd_;
  std::vector<LoanedCmdRef> eff_cmd_;
  std::vector<LoanedCmdRef> kp_cmd_;
  std::vector<LoanedCmdRef> kd_cmd_;

  // state interface refs, per joint (left, right)
  std::vector<LoanedStateRef> pos_state_;

  realtime_tools::RealtimeThreadSafeBox<geometry_msgs::msg::WrenchStamped>
      rt_contact_force_;
  rclcpp::Subscription<geometry_msgs::msg::WrenchStamped>::SharedPtr
      contact_force_subscriber_;

 private:
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

}  // namespace motkin_five_bar_force_velocity_controller

#endif  // MOTKIN_FIVE_BAR_FORCE_VELOCITY_CONTROLLER__MOTKIN_FIVE_BAR_FORCE_VELOCITY_CONTROLLER_HPP_
