version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "no changelog"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "no changelog"
    cooldown:
      default-days: 0
