<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>motkin_dual_motor_testbed_bringup</name>
  <version>1.0.0</version>
  <description>Package starting the MOTKIN dual motor testbed robot</description>
  <maintainer email="guilhem.saurel@laas.fr">Guilhem Saurel</maintainer>
  <license>Apache-2.0</license>
  <url type="repository">https://github.com/Gepetto/motkin-dual-motor-testbed-robot</url>
  <author email="olivier.stasse@laas.fr">Olivier Stasse</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>ament_cmake_auto</build_depend>
  <!-- <buildtool_depend>python3-rosdoc2</buildtool_depend> -->

  <!-- We need the xacro package to build the urdf model -->
  <exec_depend>xacro</exec_depend>
  <exec_depend>motkin_dual_motor_testbed_description</exec_depend>
  <exec_depend>motkin_forward_command_controller</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>launch_param_builder</exec_depend>
  <exec_depend>motkin_dual_motor_testbed_hardware</exec_depend>

  <!-- keep-sorted start -->
  <test_depend>ament_cmake_copyright</test_depend>
  <test_depend>ament_cmake_cppcheck</test_depend>
  <test_depend>ament_cmake_cpplint</test_depend>
  <test_depend>ament_cmake_pep257</test_depend>
  <test_depend>ament_cmake_uncrustify</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <!-- keep-sorted end -->

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
