controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    odri_fcc:
      type: odri_forward_command_controller/OdriForwardCommandController

odri_fcc:
  ros__parameters:
    joints:
      - motorL
      - motorR
    initial_command:
      motorL:
        position: 0.0
        velocity: 0.0
        effort: 0.0
        gain_kp: 0.0
        gain_kd: 0.0
      motorR:
        position: 0.0
        velocity: 0.0
        effort: 0.0
        gain_kp: 0.0
        gain_kd: 0.0
